apiVersion: v1
kind: ConfigMap
metadata:
  name: data-configuration
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "opentaxii.name" . }}
data:
  data-configuration.yml: {{.Files.Get "files/data-configuration.yml" | printf "%s" | quote}}